version: 2.1

orbs:
  vulnmap: khulnasoft-lab/vulnmap@1
  prodsec: khulnasoft-lab/prodsec-orb@1
  commitlint: conventional-changelog/commitlint@1.0.0

go_image: &go_image
  resource_class: medium
  docker:
    - image: cimg/go:1.21

node_image: &node_image
  resource_class: small
  docker:
    - image: cimg/node:21.4.0

branch_exclude_main: &branch_exclude_main
  filters:
    branches:
      ignore: [main]

branch_only_main: &branch_only_main
  filters:
    branches:
      only: main

jobs:
  lint:
    <<: *go_image
    steps:
      - checkout
      - run:
          name: run lint check
          command: make lint

  unit_test:
    <<: *go_image
    steps:
      - checkout
      - run:
          name: run unit tests with coverage
          command: make coverage
      - store_test_results:
          path: ./coverage/
      - store_artifacts:
          path: ./coverage/

  vulnmap_dep_scan:
    <<: *go_image
    steps:
      - checkout
      - vulnmap/scan:
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false

  vulnmap_code_scan:
    <<: *go_image
    steps:
      - checkout
      - vulnmap/scan:
          command: code test
          fail-on-issues: true
          severity-threshold: high
          monitor-on-build: false

  license_check:
    <<: *go_image
    steps:
      - checkout
      - run:
          name: run license check
          command: PARAM="--validate" make license

  semantic-release:
    <<: *node_image
    steps:
      - checkout
      - run:
          name: Run semantic-release
          command: make release

workflows:
  "Test":
    jobs:
      - lint:
          name: Lint
          <<: *branch_exclude_main
      - unit_test:
          name: Unit Tests
          <<: *branch_exclude_main
      - vulnmap_code_scan:
          name: Vulnmap Code Scan
          context:
            - team-lumos
            - vulnmap-bot-slack
          <<: *branch_exclude_main
      - vulnmap_dep_scan:
          name: Vulnmap Dependencies Scan
          context:
            - team-lumos
            - vulnmap-bot-slack
          <<: *branch_exclude_main
      - prodsec/secrets-scan:
          name: Secrets scan
          context:
            - vulnmap-bot-slack
          channel: lumos-alerts
          <<: *branch_exclude_main
      - commitlint/lint:
          name: Commit Lint
          <<: *branch_exclude_main
      - license_check:
          name: License Check
          <<: *branch_exclude_main

  "Release":
    jobs:
      - lint:
          name: Lint
          <<: *branch_only_main
      - unit_test:
          name: Unit Tests
          <<: *branch_only_main
      - semantic-release:
          name: Semantic Release
          context:
            - nodejs-app-release
            - team-lumos
          requires:
            - "Lint"
            - "Unit Tests"
          <<: *branch_only_main